GET http://localhost:3000/api/users

####
GET http://localhost:3000/api/users/students
####
GET http://localhost:3000/api/users/males


####
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Bob"
}